"""fix base models

Revision ID: c8530afbd406
Revises: b35d6792dc70
Create Date: 2025-06-11 22:20:04.878216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c8530afbd406'
down_revision: Union[str, None] = 'b35d6792dc70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor', sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('patient', sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('patient', sa.Column('cpf', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('patient', 'age')
    op.drop_column('patient', 'phone')
    op.drop_column('patient', 'address')
    op.add_column('specialty', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('specialty', 'description')
    op.add_column('patient', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('patient', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('patient', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('patient', 'cpf')
    op.drop_column('patient', 'email')
    op.drop_column('doctor', 'email')
    # ### end Alembic commands ###
