"""adição campo cpf a tabela autor

Revision ID: 52a31fe855a2
Revises: a888152b3ee2
Create Date: 2025-06-07 16:48:11.895115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52a31fe855a2'
down_revision: Union[str, None] = 'a888152b3ee2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('autor', sa.Column('cpf', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'autor', ['cpf'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'autor', type_='unique')
    op.drop_column('autor', 'cpf')
    # ### end Alembic commands ###
